// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/api/runtime/vcuda/api.proto

/*
Package vcuda is a generated protocol buffer package.

It is generated from these files:
	pkg/api/runtime/vcuda/api.proto

It has these top-level messages:
	VDeviceRequest
	VDeviceResponse
	VContainerIdRequest
	VContainerIdResponse
*/
package vcuda

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type VDeviceRequest struct {
	BusId         string `protobuf:"bytes,1,opt,name=bus_id,json=busId" json:"bus_id,omitempty"`
	PodUid        string `protobuf:"bytes,2,opt,name=pod_uid,json=podUid" json:"pod_uid,omitempty"`
	ContainerName string `protobuf:"bytes,3,opt,name=container_name,json=containerName" json:"container_name,omitempty"`
	ContainerId   string `protobuf:"bytes,4,opt,name=container_id,json=containerId" json:"container_id,omitempty"`
}

func (m *VDeviceRequest) Reset()                    { *m = VDeviceRequest{} }
func (m *VDeviceRequest) String() string            { return proto.CompactTextString(m) }
func (*VDeviceRequest) ProtoMessage()               {}
func (*VDeviceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *VDeviceRequest) GetBusId() string {
	if m != nil {
		return m.BusId
	}
	return ""
}

func (m *VDeviceRequest) GetPodUid() string {
	if m != nil {
		return m.PodUid
	}
	return ""
}

func (m *VDeviceRequest) GetContainerName() string {
	if m != nil {
		return m.ContainerName
	}
	return ""
}

func (m *VDeviceRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

type VDeviceResponse struct {
}

func (m *VDeviceResponse) Reset()                    { *m = VDeviceResponse{} }
func (m *VDeviceResponse) String() string            { return proto.CompactTextString(m) }
func (*VDeviceResponse) ProtoMessage()               {}
func (*VDeviceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type VContainerIdRequest struct {
	PodUid string `protobuf:"bytes,1,opt,name=pod_uid,json=podUid" json:"pod_uid,omitempty"`
}

func (m *VContainerIdRequest) Reset()                    { *m = VContainerIdRequest{} }
func (m *VContainerIdRequest) String() string            { return proto.CompactTextString(m) }
func (*VContainerIdRequest) ProtoMessage()               {}
func (*VContainerIdRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *VContainerIdRequest) GetPodUid() string {
	if m != nil {
		return m.PodUid
	}
	return ""
}

type VContainerIdResponse struct {
	ContainerId   string `protobuf:"bytes,1,opt,name=container_id,json=containerId" json:"container_id,omitempty"`
	ContainerName string `protobuf:"bytes,2,opt,name=container_name,json=containerName" json:"container_name,omitempty"`
}

func (m *VContainerIdResponse) Reset()                    { *m = VContainerIdResponse{} }
func (m *VContainerIdResponse) String() string            { return proto.CompactTextString(m) }
func (*VContainerIdResponse) ProtoMessage()               {}
func (*VContainerIdResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *VContainerIdResponse) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *VContainerIdResponse) GetContainerName() string {
	if m != nil {
		return m.ContainerName
	}
	return ""
}

func init() {
	proto.RegisterType((*VDeviceRequest)(nil), "vcuda.VDeviceRequest")
	proto.RegisterType((*VDeviceResponse)(nil), "vcuda.VDeviceResponse")
	proto.RegisterType((*VContainerIdRequest)(nil), "vcuda.VContainerIdRequest")
	proto.RegisterType((*VContainerIdResponse)(nil), "vcuda.VContainerIdResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for VCUDAService service

type VCUDAServiceClient interface {
	RegisterVDevice(ctx context.Context, in *VDeviceRequest, opts ...grpc.CallOption) (*VDeviceResponse, error)
	GetContainerIdWithPodUid(ctx context.Context, in *VContainerIdRequest, opts ...grpc.CallOption) (*VContainerIdResponse, error)
}

type vCUDAServiceClient struct {
	cc *grpc.ClientConn
}

func NewVCUDAServiceClient(cc *grpc.ClientConn) VCUDAServiceClient {
	return &vCUDAServiceClient{cc}
}

func (c *vCUDAServiceClient) RegisterVDevice(ctx context.Context, in *VDeviceRequest, opts ...grpc.CallOption) (*VDeviceResponse, error) {
	out := new(VDeviceResponse)
	err := grpc.Invoke(ctx, "/vcuda.VCUDAService/RegisterVDevice", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vCUDAServiceClient) GetContainerIdWithPodUid(ctx context.Context, in *VContainerIdRequest, opts ...grpc.CallOption) (*VContainerIdResponse, error) {
	out := new(VContainerIdResponse)
	err := grpc.Invoke(ctx, "/vcuda.VCUDAService/GetContainerIdWithPodUid", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for VCUDAService service

type VCUDAServiceServer interface {
	RegisterVDevice(context.Context, *VDeviceRequest) (*VDeviceResponse, error)
	GetContainerIdWithPodUid(context.Context, *VContainerIdRequest) (*VContainerIdResponse, error)
}

func RegisterVCUDAServiceServer(s *grpc.Server, srv VCUDAServiceServer) {
	s.RegisterService(&_VCUDAService_serviceDesc, srv)
}

func _VCUDAService_RegisterVDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VCUDAServiceServer).RegisterVDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vcuda.VCUDAService/RegisterVDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VCUDAServiceServer).RegisterVDevice(ctx, req.(*VDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VCUDAService_GetContainerIdWithPodUid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VContainerIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VCUDAServiceServer).GetContainerIdWithPodUid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vcuda.VCUDAService/GetContainerIdWithPodUid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VCUDAServiceServer).GetContainerIdWithPodUid(ctx, req.(*VContainerIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VCUDAService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "vcuda.VCUDAService",
	HandlerType: (*VCUDAServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterVDevice",
			Handler:    _VCUDAService_RegisterVDevice_Handler,
		},
		{
			MethodName: "GetContainerIdWithPodUid",
			Handler:    _VCUDAService_GetContainerIdWithPodUid_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/api/runtime/vcuda/api.proto",
}

func init() { proto.RegisterFile("pkg/api/runtime/vcuda/api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x91, 0x41, 0x4e, 0xf3, 0x30,
	0x10, 0x85, 0x7f, 0xf7, 0xa7, 0x45, 0x0c, 0xa5, 0x15, 0x86, 0x42, 0x54, 0x16, 0x40, 0x24, 0x24,
	0x56, 0xa9, 0x04, 0x27, 0x80, 0x56, 0x42, 0xdd, 0x20, 0x14, 0x94, 0xb0, 0x0c, 0x49, 0x3c, 0x2a,
	0x16, 0x4a, 0x6c, 0x62, 0xbb, 0x87, 0xe0, 0x26, 0xdc, 0x12, 0xd5, 0x6d, 0xd2, 0x94, 0x64, 0xfb,
	0xe6, 0x79, 0xe6, 0x7b, 0xcf, 0x70, 0x29, 0x3f, 0x17, 0x93, 0x58, 0xf2, 0x49, 0x61, 0x72, 0xcd,
	0x33, 0x9c, 0x2c, 0x53, 0xc3, 0xe2, 0x95, 0xe2, 0xc9, 0x42, 0x68, 0x41, 0xbb, 0x56, 0x70, 0xbf,
	0x09, 0x0c, 0xc2, 0x19, 0x2e, 0x79, 0x8a, 0x3e, 0x7e, 0x19, 0x54, 0x9a, 0x8e, 0xa0, 0x97, 0x18,
	0x15, 0x71, 0xe6, 0x90, 0x2b, 0x72, 0x7b, 0xe0, 0x77, 0x13, 0xa3, 0xe6, 0x8c, 0x9e, 0xc3, 0xbe,
	0x14, 0x2c, 0x32, 0x9c, 0x39, 0x1d, 0xab, 0xf7, 0xa4, 0x60, 0x01, 0x67, 0xf4, 0x06, 0x06, 0xa9,
	0xc8, 0x75, 0xcc, 0x73, 0x2c, 0xa2, 0x3c, 0xce, 0xd0, 0xf9, 0x6f, 0xe7, 0x47, 0x95, 0xfa, 0x1c,
	0x67, 0x48, 0xaf, 0xa1, 0xbf, 0xb5, 0x71, 0xe6, 0xec, 0x59, 0xd3, 0x61, 0xa5, 0xcd, 0x99, 0x7b,
	0x0c, 0xc3, 0x8a, 0x45, 0x49, 0x91, 0x2b, 0x74, 0x3d, 0x38, 0x09, 0xa7, 0x5b, 0x4b, 0xc9, 0x58,
	0x83, 0x21, 0x75, 0x18, 0xf7, 0x1d, 0x4e, 0x77, 0xfd, 0xeb, 0x3d, 0x8d, 0xeb, 0xa4, 0x71, 0xbd,
	0x25, 0x47, 0xa7, 0x25, 0xc7, 0xdd, 0x0f, 0x81, 0x7e, 0x38, 0x0d, 0x66, 0x0f, 0xaf, 0x58, 0xac,
	0x50, 0xe9, 0x23, 0x0c, 0x7d, 0x5c, 0x70, 0xa5, 0xb1, 0xd8, 0xd0, 0xd3, 0x91, 0x67, 0xdb, 0xf5,
	0x76, 0x9b, 0x1d, 0x9f, 0xfd, 0x95, 0x37, 0x21, 0xff, 0xd1, 0x00, 0x9c, 0x27, 0xd4, 0x35, 0xf0,
	0x37, 0xae, 0x3f, 0x5e, 0xd6, 0xfd, 0x8e, 0xcb, 0x57, 0xcd, 0x1e, 0xc6, 0x17, 0xad, 0xb3, 0x72,
	0x6d, 0xd2, 0xb3, 0x7f, 0x7d, 0xff, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x34, 0x77, 0xfd, 0xd2, 0x0e,
	0x02, 0x00, 0x00,
}
